"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Auto_1 = require("./Auto");
var RegistroAutomotor_1 = require("./RegistroAutomotor");
var registro = new RegistroAutomotor_1.RegistroAutomotor;
var auto1 = new Auto_1.Auto("Ford", "Lucas", "Aa654SC");
var auto2 = new Auto_1.Auto("Ferrari", "Franco", "Aa654SB");
var auto3 = new Auto_1.Auto("Ford", "Kevin", "AC789SC");
var auto4 = new Auto_1.Auto("Lamborghini", "Ayelen", "Aj654SC");
var auto5 = new Auto_1.Auto("Buggati", "Mario", "Aa654SC");
registro.darDeAlta(auto1);
registro.darDeAlta(auto2);
registro.darDeAlta(auto3);
registro.darDeAlta(auto4);
registro.darDeAlta(auto5);
console.log("------------------------");
registro.listarRegistro();
console.log("--------------------------");
registro.eliminarAuto("Aa654SC");
console.log("--------------------------");
registro.actualizarAuto("AC789SC");
console.log("--------------------------");
registro.buscarPatete("Aa654SB");
console.log("--------------------------");
registro.buscarPatete("Aa654iB");
console.log("--------------------------");
registro.listarRegistro();
